server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: ${EUREKA_USERNAME:admin}
      password: ${EUREKA_PASSWORD:admin}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOSTNAME:localhost}:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 30000
    enable-self-preservation: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://tempo:4318/v1/traces}