server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/code-rana-arijit/Medikit-Config.git}
          default-label: main
          clone-on-start: true
          timeout: 30
          force-pull: true
        bootstrap: true
  security:
    user:
      name: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD:config}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://tempo:4318/v1/traces}