apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: medikit
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: user-service
          image: ghcr.io/code-rana-arijit/medikit/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8101
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: medikit-common-config
                  key: EUREKA_SERVER
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: medikit-common-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: medikit-common-config
                  key: REDIS_PORT
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: medikit-common-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: medikit-common-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: medikit-common-config
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: medikit-db-config
                  key: user-service-db-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: medikit-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8101
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8101
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: medikit
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8101
      targetPort: 8101
      name: http
